---
automation:
  - alias: "Alter basement lights when cat mode is on"
    id: "alter_basement_lights_when_cat_mode_is_on"

    trigger:
      - platform: time
        id: morning
        at: "09:00:00"

      - platform: time
        id: night
        at: "21:00:00"

    condition:
      - condition: state
        entity_id: input_boolean.cat_mode
        state: "on"

    action:
      - choose:
          - alias: "Manage morning"
            conditions:
              condition: trigger
              id: morning

            sequence:
              - alias: "Turn the basement lights on"
                service: homeassistant.turn_on
                target:
                  entity_id: switch.basement_lights

          - alias: "Manage night"
            conditions:
              condition: trigger
              id: night

            sequence:
              - alias: "Turn the basement lights on"
                service: homeassistant.turn_off
                target:
                  entity_id: switch.basement_lights
